import type { Product, ProductCategory } from "./traceabilityApi";

const manualDate = "............";

const zoneByCategory: Record<ProductCategory, string> = {
  boulangerie: "PBC1",
  cake: "PBC2",
  patisserie: "PBC2",
  beldi: "PBC3",
  viennoiserie: "PBC4",
};

const codesByCategory: Record<ProductCategory, Record<string, string>> = {
  boulangerie: {
    "BAGUETTE ANCIENNE": "01",
    "BAGUETTE ANCINNE": "01",
    "BAGUETTE CEREALE": "02",
    "BAGUETTE CERIALE": "02",
    "BAGUETTE COMPLET": "03",
    "BAGUETTE NORMAL": "04",
    "BAGUETTE OLIVES": "05",
    "BAGUETTE OLIVE": "05",
    "BAGUETTE PAVOT": "06",
    "BAGUETTE SEMOULE": "07",
    "BAGUETTE SESAM": "08",
    "BAGUETTE SESAME": "08",
    CHABATA: "09",
    CAHABTA: "09",
    "PAIN AU LAIT": "10",
    "PAIN AU LAIT CHOCOLAT": "11",
    "PAIN BOLLE": "12",
    "PAIN COMPLET": "13",
    "PAIN COMPLET S SEL": "14",
    "PAIN COMPLET SANS SEL": "14",
    "PAIN MAIS": "15",
    "PAIN ORGE": "16",
    "PAIN ORGE OLIVE": "17",
    "PAIN SEMOULE": "18",
    "PAIN SEMOULE S SEL": "19",
    "PAIN SEMOULE SANS SEL": "19",
    "SANDWICH COMPLET": "20",
    "SANDWICHE COMPLET": "20",
    "SANDWICH OLIVES": "21",
    "SANDWICH OLIVE": "21",
    "SANDWICHE OLIVE": "21",
    "SANDWICH OLIVE VERT ET MOZZARELLA": "22",
    "SANDWICHE OLIVE VERT ET MOZZARELLA": "22",
    "SANDWICH PAVOT": "23",
    "SANDWICHE PAVOT": "23",
    "SANDWICH SEMOULE": "24",
    "SANDWICHE SEMOULE": "24",
    "SANDWICH SESAM": "25",
    "SANDWICH SESAME": "25",
    "SANDWICHE SESAME": "25",
  },
  beldi: {
    FEKKAS: "01",
    "FEKKAS S SUCRE": "02",
    BAHLA: "03",
    "M7ANCHA HACHEE": "04",
    "MHENCHA NORMAL": "04",
    RICHBOND: "05",
    SBANI: "06",
    "SBANNI GR": "06",
    "SBANI BOITE": "06b",
    "SEBBANI BOITES": "06b",
    "SBANI PLATEAU": "06",
    "GHRIBA EFFILEE CAFE": "GEC",
    "GHRIBA EFFILEES CAFE": "GEC",
    "CORNE DE GAZELLE": "07",
    "CORNE DE GAZELLE BLUE": "07",
    "CORNE DE GAZELLE BLUE INDIGO": "07",
    "CORNE DE GAZELLE ROUGE": "07",
    "CORNE DE GAZELLE NOIR": "07",
    "GHRIBA EFFILEES": "08",
    "GHRIBA EFILLEES": "08",
    "COOKIES DROPS": "09",
    "COOKIES DROPSS": "09",
    GARGA3A: "10",
    "M7ANCHA AMANDE": "11",
    "GHRIBA SUCRE GLACE": "12",
    DIAMANTINE: "13",
    "SABLE DIAMANTINE": "13",
    BAKLAVA: "14",
    "M7ANCHA LOUZ": "15",
    "MHENCHA AMANDE": "15",
    "MHENCHA PRALINE AMANDE": "15",
    "COOKIES DROPS PISTACHE": "16",
    "RAFFAELLO COCO": "RC",
    "RAFAELLO COCO": "RC",
    "RAFFAELLO KUNAFA": "RK",
    "RAFAELLO KOUNAFA": "RK",
    CHAHDA: "CH",
    "SABLE CARAMEL": "SC",
    "SABLE PISTACHE": "SP",
    "SABLE CAFE": "SCF",
    "SABLE CITRON": "SCi",
    "TARTE FRUIT SECS": "TFS",
  },
  viennoiserie: {
    "PAIN CHOCOLAT": "01",
    "CROISSANT SIMPLE": "02",
    "CROISSANT SIMPLE PATE AMANDE": "03",
    "CROISSANT SIMPLE CREME AMANDE": "04",
    "PAIN RAISIN": "05",
    "DOUBLE CHNEQUE": "06",
    "PAIN SUISSE": "07",
    "DANISH PECHE": "08",
    PETRISSE: "09",
    KRACHEL: "10",
    "CROISSANT NOISETTE": "11",
    DONAT: "12",
    "DONAT N": "12-1",
    "DONAT B": "12-2",
    "DONAT R": "12-3",
    BEIGHNETS: "13",
    "BEIGHNETS C": "13-1",
    "BEIGHNETS F": "13-2",
    "CHAUSSON POMME": "14",
    "CHAUSSON JALOUSIE AMANDE": "15",
    "BAGUETTE PALMIER SUCRE": "16",
    "BAGUETTE PALMIER CHOCOLAT": "17",
    SACRISTAIN: "18",
    "CROISSANT SIMPLE CITRON": "19",
    "CROISSANT SIMPLE FRAMOISE": "20",
    "CROISSANT SIMPLE CHOCOLAT": "21",
    "CROISSANT SIMPLE CARAMEL": "22",
    "CROISSANT SIMPLE PISTACHE": "24",
  },
  patisserie: {
    OPERA: "01",
    "MACARON PRALINE": "02",
    TROPICAL: "03",
    YAOURT: "04",
    NOISIOLLA: "05",
    NOISIOLA: "05",
    "3 CHOCOLAT": "06",
    "FORET NOIRE": "07",
    TERAMISSU: "08",
    TIRAMISU: "08",
    "RED VELVET": "09",
    "BISCUIT PAVOT": "10",
    "CHEESECAKE CITRON": "16",
    "CHEESECAKE LOTUS": "16",
    "CHEESECAKE MANGUE": "16",
    "CHEESECAKE MERTIL": "16",
    "CHEESECAKE MYRTILLE": "16",
    "CHEESECAKE FRAMBOISE": "16",
    "MILLE FEUILLE VANILLE": "22",
    "MILLE FEUILLE CHOCOLAT": "22",
    "MACARON COEUR BLANC": "39",
    "MACARON COEUR BLUE": "39",
    "MACARON COEUR JAUNE": "39",
    "MACARON COEUR NOIR": "39",
    "MACARON COEUR ROUGE": "39",
    "MACARON COEUR VERT": "39",
    "MACARON PETIT BLANC": "39",
    "MACARON PETIT BLUE": "39",
    "MACARON PETIT JAUNE": "39",
    "MACARON PETIT NOIR": "39",
    "MACARON PETIT ROUGE": "39",
    "MACARON PETIT VERT": "39",
  },
  cake: {
    "CAKE ROYALE": "26",
    "COOKIES AMERICAINS": "27-1",
    "COOKIES FRAMOISE GR": "27-2",
    "COOKIES NOISSETE GR": "27-2",
    "COOKIES NOISETTE GR": "27-2",
    "COOKIES PISTACH GR": "27-2",
    "FONDANT CHOCOLAT": "30",
    "BROWNIE NOIX": "31",
    "BROWNIE NOISETTE": "32",
    "CAKE GR AMANDES": "33",
    "CAKE GR AMANDE": "33",
    "CAKE GR CHOCOLAT": "33",
    "CAKE GR VANILLE": "33",
    "CAKE DATTES": "34",
    "HONEY CAKE": "35",
    "MADELEINE SIMPLE": "29",
    "MADELEINE CHOCOLAT": "29",
    "MILLE FEUILLE VANILLE": "22",
    "MILLE FEUILLE CHOCOLAT": "22",
    "FERRERO AMERICAN CAKE": "23",
    "NOUGA AMERICAN CAKE": "23",
    "NUTELLA AMERICAIN CAKE": "23",
    "TARTE AMANDE": "37",
    "TARTE CHOCOLAT": "37",
    "TARTE CITRON": "37",
    "TARTE FRAMBOISE": "37",
    "TARTE NOIX": "37",
    "TARTE PARIS BREST": "37",
    "TARTE POMME": "37",
    "TARTE SOLEIL": "37",
  },
};

export function generateProductionLotNumber(product: Product | null, productionDate: string) {
  if (!product?.category) return "";
  const zone = zoneByCategory[product.category];
  const code = codeForProduct(product.category, product.name) ?? "??";
  return `${zone}${code}-${dateSuffix(productionDate) ?? manualDate}`;
}

function codeForProduct(category: ProductCategory, name: string) {
  return codesByCategory[category][normalizeCodeKey(name)];
}

function dateSuffix(value: string) {
  const match = value.trim().match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (!match) return null;
  return `${match[3]}${match[2]}${match[1].slice(2)}`;
}

function normalizeCodeKey(value: string) {
  return value
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toUpperCase()
    .replace(/[.\-/]/g, " ")
    .replace(/[^A-Z0-9]+/g, " ")
    .trim()
    .replace(/\s+/g, " ");
}
