-- Generated by generate_clean_traceability_import_sql.py.
-- Safe to run after reset_traceability_business_data.sql.

begin;

with supplier_input(name) as (
  values
  ('CREATIVE DISTRIBUTION'),
  ('DIVERS'),
  ('ECOMAB'),
  ('LACTO GROUP'),
  ('MANARA PRODUCTS'),
  ('MILKY FOOD'),
  ('OUMOUZOUN DISTRIBUTION'),
  ('OVODIC'),
  ('OVOTEC'),
  ('PANNA NEGOCE'),
  ('RAFII'),
  ('RICA MAROC'),
  ('SOCRECH'),
  ('SONIPALE')
)
insert into suppliers (name, is_active)
select name, true
from supplier_input
on conflict (name) do update
set is_active = excluded.is_active;

with material_input(name, supplier_name, unit) as (
  values
  ('Ananas conserve', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Arôme café', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Arôme citron', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Arôme orange', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Arôme pistache', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Beurre Bonna', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Cerises Amarena', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Colorant', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Colorant blanc', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Colorant jaune', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Colorant noir', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Colorant orange', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Colorant pistache', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Colorant rouge', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Colorant vert', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Confiture', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Confiture Zakia', 'CREATIVE DISTRIBUTION', 'kg'),
  ('conserve pèche', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Crème caramel', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Crème pistache', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Gala blanc', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Gala noir', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Glucose', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Gélatine poudre', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Levure chimique', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Nappage NEUTRE', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Nappage normal', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Poudre vanille', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Sucre glacé', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Vermicelle', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Vermicelle noire', 'CREATIVE DISTRIBUTION', 'kg'),
  ('Acajou', 'DIVERS', 'kg'),
  ('Agar-agar', 'DIVERS', 'kg'),
  ('Ananas', 'DIVERS', 'kg'),
  ('arachide', 'DIVERS', 'kg'),
  ('Banane', 'DIVERS', 'kg'),
  ('Beurre rigale', 'DIVERS', 'kg'),
  ('Bicarbonate de soude', 'DIVERS', 'kg'),
  ('Biscuit lotus', 'DIVERS', 'kg'),
  ('Cannelle', 'DIVERS', 'kg'),
  ('Citron', 'DIVERS', 'kg'),
  ('Cornflower', 'DIVERS', 'kg'),
  ('Danone perle', 'DIVERS', 'kg'),
  ('Dattes', 'DIVERS', 'kg'),
  ('Eau', 'DIVERS', 'L'),
  ('Eau de fleur', 'DIVERS', 'L'),
  ('Fenouil', 'DIVERS', 'kg'),
  ('Ferrero', 'DIVERS', 'kg'),
  ('Framboise', 'DIVERS', 'kg'),
  ('Gingembre', 'DIVERS', 'kg'),
  ('Kitkat', 'DIVERS', 'kg'),
  ('Konafa', 'DIVERS', 'kg'),
  ('Levure', 'DIVERS', 'kg'),
  ('Mangue', 'DIVERS', 'kg'),
  ('Miel', 'DIVERS', 'kg'),
  ('Nestlé', 'DIVERS', 'kg'),
  ('Nestlé caramel', 'DIVERS', 'kg'),
  ('Nutella', 'DIVERS', 'kg'),
  ('Philadelphia', 'DIVERS', 'kg'),
  ('Pomme', 'DIVERS', 'kg'),
  ('Pétales de fleurs', 'DIVERS', 'kg'),
  ('Raisin', 'DIVERS', 'kg'),
  ('Sel', 'DIVERS', 'kg'),
  ('Sucre cassonade', 'DIVERS', 'kg'),
  ('Sucre semoule', 'DIVERS', 'kg'),
  ('Sésame', 'DIVERS', 'kg'),
  ('Tournesol', 'DIVERS', 'kg'),
  ('Vinaigre', 'DIVERS', 'kg'),
  ('Xanthane', 'DIVERS', 'kg'),
  ('Yaourt poudre', 'DIVERS', 'kg'),
  ('Amande effilée', 'ECOMAB', 'kg'),
  ('Amande hachée', 'ECOMAB', 'kg'),
  ('Amande poudre', 'ECOMAB', 'kg'),
  ('Beurre de cacao', 'ECOMAB', 'kg'),
  ('Choco noire callebaut', 'ECOMAB', 'kg'),
  ('Chocolat au lait Callebaut', 'ECOMAB', 'kg'),
  ('Chocolat batoni', 'ECOMAB', 'kg'),
  ('Chocolat blanc Callebaut', 'ECOMAB', 'kg'),
  ('Chocolat caramel', 'ECOMAB', 'kg'),
  ('Chocolat noir Callebaut', 'ECOMAB', 'kg'),
  ('Ecorces d''orange', 'ECOMAB', 'kg'),
  ('Extrait liquide café', 'ECOMAB', 'kg'),
  ('Feuilletine', 'ECOMAB', 'kg'),
  ('Fondant', 'ECOMAB', 'kg'),
  ('Gousse de vanille', 'ECOMAB', 'kg'),
  ('Gélatine feuille', 'ECOMAB', 'kg'),
  ('Maïzena', 'ECOMAB', 'kg'),
  ('Mélange de graines', 'ECOMAB', 'kg'),
  ('Noix', 'ECOMAB', 'kg'),
  ('Pate pistache', 'ECOMAB', 'kg'),
  ('Pectine NH', 'ECOMAB', 'kg'),
  ('Pistache', 'ECOMAB', 'kg'),
  ('Poudre cacao', 'ECOMAB', 'kg'),
  ('Poudre pâtissière', 'ECOMAB', 'kg'),
  ('Purée abricot', 'ECOMAB', 'kg'),
  ('Purée ananas', 'ECOMAB', 'kg'),
  ('Purée banane', 'ECOMAB', 'kg'),
  ('Purée citron', 'ECOMAB', 'kg'),
  ('Purée coco', 'ECOMAB', 'kg'),
  ('Purée framboise', 'ECOMAB', 'kg'),
  ('Purée fruit', 'ECOMAB', 'kg'),
  ('Purée mangue', 'ECOMAB', 'kg'),
  ('Purée myrtille', 'ECOMAB', 'kg'),
  ('Purée passion', 'ECOMAB', 'kg'),
  ('Sucre glace spécial', 'ECOMAB', 'kg'),
  ('Trimoline', 'ECOMAB', 'kg'),
  ('Beurre', 'LACTO GROUP', 'kg'),
  ('Amande noire', 'MANARA PRODUCTS', 'kg'),
  ('Noisette', 'MANARA PRODUCTS', 'kg'),
  ('Fromage blanc', 'MILKY FOOD', 'kg'),
  ('Huile', 'OUMOUZOUN DISTRIBUTION', 'L'),
  ('Œufs', 'OVODIC', 'piece'),
  ('Blanc d''œuf', 'OVOTEC', 'piece'),
  ('Jaune d''œuf', 'OVOTEC', 'piece'),
  ('Chocolat au lait Lubeca', 'PANNA NEGOCE', 'kg'),
  ('Chocolat blanc Lubeca', 'PANNA NEGOCE', 'kg'),
  ('Chocolat noir Lubeca', 'PANNA NEGOCE', 'kg'),
  ('Drops', 'PANNA NEGOCE', 'kg'),
  ('Lait', 'RAFII', 'L'),
  ('Farine', 'RICA MAROC', 'kg'),
  ('Farine force', 'RICA MAROC', 'kg'),
  ('Farine viennoiserie', 'RICA MAROC', 'kg'),
  ('Nkhaala', 'RICA MAROC', 'kg'),
  ('Crème fraîche', 'SOCRECH', 'kg'),
  ('Améliorant', 'SONIPALE', 'kg'),
  ('Levure Jaouda', 'SONIPALE', 'kg')
),
inserted_products as (
  insert into products (code, name, type, unit)
  select
    'MP-' || upper(substr(md5(input.name), 1, 12)),
    input.name,
    'raw'::product_type,
    input.unit
  from material_input input
  where not exists (
    select 1
    from products existing
    where existing.type = 'raw'
      and lower(trim(existing.name)) = lower(trim(input.name))
  )
  on conflict (code) do nothing
  returning id, name
),
updated_existing_products as (
  update products
  set unit = input.unit,
      is_active = true,
      updated_at = now()
  from material_input input
  where products.type = 'raw'
    and lower(trim(products.name)) = lower(trim(input.name))
    and (
      products.unit is distinct from input.unit
      or products.is_active is distinct from true
    )
  returning products.id, products.name
),
raw_products as (
  select products.id, products.name
  from products
  join material_input input on lower(trim(input.name)) = lower(trim(products.name))
  where products.type = 'raw'
    and products.is_active = true
  union
  select id, name
  from inserted_products
  union
  select id, name
  from updated_existing_products
),
supplier_links as (
  insert into supplier_raw_materials (supplier_id, product_id)
  select suppliers.id, raw_products.id
  from material_input input
  join suppliers on lower(trim(suppliers.name)) = lower(trim(input.supplier_name))
  join raw_products on lower(trim(raw_products.name)) = lower(trim(input.name))
  on conflict (supplier_id, product_id) do nothing
  returning product_id
)
select
  (select count(*) from material_input) as requested_raw_materials,
  (select count(*) from inserted_products) as newly_created_raw_materials,
  (select count(*) from supplier_links) as newly_created_supplier_links,
  (select count(*) from raw_products) as total_raw_materials_found;

commit;
